### ISSUE TITLE
Don't use bot token directly

### ISSUE THREAD

**Issue by sharan-aithal** [Roshaen/tele-bot#1]
Your telegram bot's token can be found in git commits. It is insecure to use these credentials here. It can be used by anyone to control your bot.
You should remove these tokens from the code.

You can always revoke bot's token by Botfather (https://t.me/botfather).

My suggestion is to use environment variables in future instead using credentials/secrets directly in your code.

For more info [about bot](https://core.telegram.org/bots#creating-a-new-bot)

**Comment by youhaveme9** [comment]
@sharan-aithal thanks for your suggestion 😀
